### ISSUE TITLE
Error in jolie for windows

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/jolie#528] opened 2024-09-30 18:48 UTC
The Windows version of JOLIE, whether installed by downloading the binary or built locally with `mvn clean` install, gives me the error "*Cannot invoke "jolie.State.root()" because the return value of "jolie.ExecutionThread.getState()" is null*" when running any .ol file.

**To Reproduce**
git clone https://github.com/jolie/jolie.git
cd jolie
mvn install

set uo enviroment variable JOLIE_HOME to directory and copy dist in this directory and the launcher in bin subdir. Add the bin subdir to path.
jolie -h is correct
jolie file.ol 
==  > Cannot invoke "jolie.State.root()" because the return value of "jolie.ExecutionThread.getState()

**Expected behavior**
I expect run of file.ol

**Desktop (please complete the following information):**
 - OS: Windows
 - Jolie version master tree
 - Java Version 21

**Comment by mwallnoefer** [comment] 2024-11-10 11:02
Jolie 1.12.2 with Java 21 on Windows 10 works, so it has to do with the latest changes done in git.

**Comment by fmontesi** [comment] 2024-11-13 13:28
Is this bug still there?

**Comment by Niels-Erik** [comment] 2024-11-28 21:32
I've just gotten this "bug" on my desktop pc today.
However I think it comes after I was cleaning my C drive to get more space, since it worked before that.
I have tried to reinstall java jdk 21 and jolie 1.12.2.

**Comment by Niels-Erik** [comment] 2024-11-28 21:47
I forgot that I cannot run Jolie files that is in any subfolder of my user, since there is a space in my name, Niels Erik...
However I have found a way to reproduce the bug, by trying to the following code:
```
interface addInterface {
    RequestResponse: 
    add(int)(int)
}

service bug {

    inputPort httpPort {
        Location: "socket://localhost:8080" 
        protocol: http {.format = json}
        interfaces: addInterface
    }

    main{
        
        [add(req)(res){
            res = req++
        }]
    }
}
```
This would run if you delete the `{.format = json}` part.
The stacktrace from running with --stacktrace is:
```
java.lang.NullPointerException: Cannot invoke "jolie.State.root()" because the return value of "jolie.ExecutionThread.getState()" is null
        at jolie.runtime.VariablePath.getRootValue(VariablePath.java:129)
        at jolie.runtime.VariablePath.getValueOrNull(VariablePath.java:243)
        at jolie.runtime.VariablePath.evaluate(VariablePath.java:444)
        at jolie.runtime.expression.InlineTreeExpression$AssignmentOperation.run(InlineTreeExpression.java:90)
        at jolie.runtime.expression.InlineTreeExpression.evaluate(InlineTreeExpression.java:143)
        at jolie.OOITBuilder.visit(OOITBuilder.java:509)
        at jolie.lang.parse.UnitOLVisitor.visit(UnitOLVisitor.java:429)
        at jolie.lang.parse.UnitOLVisitor.visit(UnitOLVisitor.java:92)
        at jolie.lang.parse.ast.InputPortInfo.accept(InputPortInfo.java:85)
        at jolie.lang.parse.ast.OLSyntaxNode.accept(OLSyntaxNode.java:47)
        at jolie.OOITBuilder.visit(OOITBuilder.java:615)
        at jolie.OOITBuilder.build(OOITBuilder.java:216)
        at jolie.Interpreter.buildOOIT(Interpreter.java:1239)
        at jolie.Interpreter.init(Interpreter.java:996)
        at jolie.Interpreter.run(Interpreter.java:1079)
        at jolie.Jolie.main(Jolie.java:86)
```

**Comment by kicito** [comment] 2024-11-29 10:31
Will the program run if you use `{.format = "json"}`?

`{.format = json}` tells jolie to evaluate the value of 'json' field from the service parameter. A clearer error message would definitely help trace the issue here.

**Comment by Niels-Erik** [comment] 2024-11-29 11:17
> Will the program run if you use `{.format = "json"}`?
yes, it will also run if i made json a constant equal to "json".

I looked into the code and the issue is that Jolie is still in a early "startup" phase, so when it looks for the value of the variable it fails as Jolie has not even set that part up.

I was seeing if I could make a fix, and ran across the `getValueOrNull()` method, which if I made it return null if variables cannot be "found" yet which makes it run.
However would this be the correct behavior as format will be set to undefined, and it could cause headaches if someone forgot to set the constant, import it, or not put it in the service parameter, and the program then gives something "unexpected"?

**Comment by kicito** [comment] 2024-11-29 11:58
Thank you for considering this. Given that the communication port configuration should remain static throughout a single execution, I think the program should exit when an undefined value is encountered. Jolie evaluates communication libraries on initialization making it crucial to avoid undefined configurations, as they could lead to "unexpected" issues as you mentioned.

**Comment by mwallnoefer** [comment] 2024-12-15 07:25
I guess that we have identified the problem as a generic port initialisation side-effect, not strictly related to Windows as OS. So I suggest to close the issue and propose an eventual fix as a pull-request.

**Closed by mwallnoefer** 2024-12-15 07:25 UTC
Labels: bug
