### ISSUE TITLE
HTTP protocol error Rest Soap UI Load test

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#96] opened 2016-09-02 10:23 UTC
[testSoapUI.zip](https://github.com/jolie/jolie/files/454855/testSoapUI.zip)

[testSoapUI.zip](https://github.com/jolie/jolie/files/454942/testSoapUI.zip)

@fmontesi @klag 

Hi guys 

As I have said  before at @klag on the phone I am trying to run some load test for the db_connector, my testing set-up is the following
- Service with operation REST running  on window 7
- Operation implements a simple query with 100 result limit
- Target DB Postgres running on linux RedHat 
- Soap Ui load test 10 threads random 0,5  test starts every 1 s  duration 60 reperition

![image](https://cloud.githubusercontent.com/assets/12083716/18198983/b8babeee-70fe-11e6-960f-b5f7298b69c5.png)

the behavior is interesting 

![image](https://cloud.githubusercontent.com/assets/12083716/18199031/ec87354a-70fe-11e6-90d9-37b925e8869c.png)

It starts all fine around 25% of the test the HTTP server stops answering

![image](https://cloud.githubusercontent.com/assets/12083716/18199119/450c77b6-70ff-11e6-9807-ca974c0db9f3.png)

Moving the test service directly to the RedHat Server I got the same problem 

![image](https://cloud.githubusercontent.com/assets/12083716/18199461/a58eced0-7100-11e6-8fd5-3f68f5512188.png)

I switched to the old db implementation and run the test 

![image](https://cloud.githubusercontent.com/assets/12083716/18199943/db970b58-7102-11e6-85cf-d2c0ac3da8b9.png)

we do not get any error 

Any Idea ?

**Comment by fmontesi** [comment] 2016-09-06 09:06
Is this specific for db_connector? If so, could you move the issue there?

@klag any ideas?

**Comment by fmontesi** [comment] 2017-03-21 08:02
Hi all,

Nobody is discussing this. Is this still an issue?

**Comment by bmaschio** [comment] 2017-03-21 08:08
I will

**Comment by fmontesi** [comment] 2017-11-06 08:34
Closing this for now since I cannot reproduce it, please reopen if still relevant.

**Closed by fmontesi** 2017-11-06 08:34 UTC
Labels: bug
