### ISSUE TITLE
Does openapi2jolie work with swagger 2.0 files

### ISSUE THREAD

**Issue by slecholineas** [jolie/jolie#297] opened 2021-02-17 10:29 UTC
I'm using openapi2jolie to generate client code based on an existing swagger 2.0 file.

When I launch the following command
`jolie openapi2jolie.ol employee-module-v1.0.3.yaml jolie-output EmployeeService https`

I'm getting this stacktrace, so I was wondering if openapi2jolie supports Swagger 2.0 files
`Generating client...
feb. 17, 2021 11:17:08 A.M. openapi2jolie.ol
INFO: [openapi2jolie.ol] java.io.IOException: Unexpected character (s) at position 0.
        at jolie.js.JsUtils.parseJsonIntoValue(JsUtils.java:235)
        at joliex.io.FileService.readJsonIntoValue(FileService.java:185)
        at joliex.io.FileService.readFile(FileService.java:422)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at jolie.runtime.JavaService.requestResponseCallable(JavaService.java:246)
        at jolie.runtime.JavaService.callOperation(JavaService.java:339)
        at jolie.runtime.embedding.JavaCommChannel.lambda$sendImpl$0(JavaCommChannel.java:92)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: Unexpected character (s) at position 0.
        at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
        at org.json.simple.JSONValue.parseWithException(JSONValue.java:73)
        at jolie.js.JsUtils.parseJsonIntoValue(JsUtils.java:226)
        ... 14 more`

**Comment by klag** [comment] 2021-03-22 08:27
openapi2jolie does not accept yaml format so far. Try with a json one.

**Comment by mwallnoefer** [comment] 2021-07-04 19:14
This is a duplicate of issue #294.

**Closed by mwallnoefer** 2021-07-04 19:14 UTC
