### ISSUE TITLE
Embedded services should be able to automatically load all their libraries in lib folder

### ISSUE THREAD

**Issue by klag** [jolie/jolie#32] opened 2015-04-16 08:58 UTC
When a service is embedded in a parent service, it is not able to load the libraries contained in its lib folder.

It is possible to override this problem by loading libraries inside the embedded code with a loadLibrary@Runtime invocation but it is a very bad solution. The developer indeed is forced to change his programming style depending on the fact that the service will be embedded or not (and we must avoid it).

**Comment by fmontesi** [comment] 2015-04-16 09:04
That's partially incorrect I believe, but it requires testing.

I believe that a subservice can load libraries in its lib folder. The only problem is that services share a class cache with the classloader of their parents. Hence if you load a JavaService with a "CanUseJars" annotation and this gets evaluated by the embedder, you don't find the lib there and then, when the embedded service load the class, the CanUseJars annotation does not trigger another lookup for the library because the classloader picks the class from the cache (and picking from the cache does not currently trigger a reload).

The best place for looking at the reason of all this is probably JolieClassLoader and see what happens when it loads the class you're interested in.

**Comment by klag** [comment] 2015-04-16 09:34
You can solve the problem with loadLibrary for the direct embedded services, but if you have more nested services, it seems that also loadLibrary does not work.

Ex:

parent (libA,libB,libC)
     child1 (libD,libE,libF)
          child 2 (libG,libH,libI)

libD,libE and libF can be loaded by using loadLibrary@Runtime in child1.
libG, libH and libI cannot be loaded

**Comment by fmontesi** [comment] 2015-04-17 07:53
What the... :-)

OK, please create a brief test to reproduce it. I suggest you create a git repo in your github account that everybody can clone to test it.

**Comment by mwallnoefer** [comment] 2015-08-24 19:21
Any news here, seems to be an interesting issue...

**Comment by fmontesi** [comment] 2015-08-25 06:24
Not yet, @klag promised to produce a small test as soon as he finds the time.

**Comment by bmaschio** [comment] 2015-09-08 15:14
@fmontesi @mwallnoefer @klag It would be useful to have a repository with all the example for testing and new implementation

**Comment by fmontesi** [comment] 2015-09-10 16:17
@klag have you been able to reproduce the bug?

**Comment by fmontesi** [comment] 2017-11-06 08:42
Closing this for now, please apply https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html and reopen the issue in case it's still relevant.

**Closed by fmontesi** 2017-11-06 08:42 UTC
Labels: bug
