### ISSUE TITLE
HTTPS machine Killer

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#125] opened 2018-02-22 18:54 UTC
Hi all @jolie/developers 
I have noticed with https in jolie

Some general info

Jolie Version : 1.6.0
Java Version : Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
OS : Linux / WIndows

My port looks like
````js
inputPort HttpsInput {
  Location:"socket://localhost:14001"
  Protocol: https {
	   .keepAlive = false; // Keep connections open
	   .debug = DebugHttp;
	   .debug.showContent = DebugHttpContent;
	   .format -> format;
	   .contentType -> mime;
           .statusCode -> statusCode;
	   .default = "default";
           .ssl.keyStore = "./ssl/KeyStore.jks";
	    .ssl.keyStorePassword ="a4KPCrUxShYsjkhQ"

   }
   Interfaces: HTTPInterface
}
````
the first one is that I get some termination  with a GET 

https://localhost:14001/js/jquery-1.12.2.js

![image](https://user-images.githubusercontent.com/12083716/36557077-843eae62-1807-11e8-86c2-d5c2625510b1.png)

Plus I get some machine killer behaviour under windows 

![image](https://user-images.githubusercontent.com/12083716/36557020-6017fdb8-1807-11e8-82f3-1efda29c0c25.png)

![image](https://user-images.githubusercontent.com/12083716/36557369-5c52223e-1808-11e8-9ec5-36b89a827600.png)

I thought that the problem was only limited to Windows ( the smurfs OS ) but no I get the same problem with linux

![image](https://user-images.githubusercontent.com/12083716/36556898-ff1d3d70-1806-11e8-990b-aa2b58782144.png)

![image](https://user-images.githubusercontent.com/12083716/36557513-c0daf51e-1808-11e8-88c9-b5127249a3a5.png)

Am I doing something wrong?

PS: there is flight_recording java
[flight_recording_180151CJolie160joliejar12184_2018-02-22_18-36-23_b9ed92c.zip](https://github.com/jolie/jolie/files/1749168/flight_recording_180151CJolie160joliejar12184_2018-02-22_18-36-23_b9ed92c.zip)

Cheers
Balint

**Comment by fmontesi** [comment] 2018-02-23 08:09
Hi Balint,

Can you produce a test, per https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html, or at least a minimal example that reproduces this bug with the latest version of Jolie?

Cheers,
F

**Comment by bmaschio** [comment] 2018-02-23 09:41
@fmontesi 

Hi have created a brunch Error125 with the example

/test/extensions/leonardo_https.ol

I did not get the ERROR_CONTENT_LENGHT I believe due to the simplicity of the example, when I was reporting was more a complex web project with more link and resources.

But I manage to reproduce the killing behavior  ( the server does not respond after the first round of HTTP get)
Cheers
Balint

**Comment by fmontesi** [comment] 2018-02-23 11:48
Hi Balint,

I cannot run your test (see below). You can find help/instructions and a template here: https://jolielang.gitbooks.io/developer-guide/content/tests.html

```
% jolie test.ol "leonardo.*"                                                                                                                                                                                                                     leonardo_https.ol...  Feb 23, 2018 12:46:07 PM jolie.Interpreter logWarning
WARNING: [leonardo_https.ol] Received a message for operation test, not specified in the input port at the receiving service. Sending IOException to the caller.
Feb 23, 2018 12:46:07 PM jolie.Interpreter logInfo
INFO: [leonardo_https.ol] java.io.FileNotFoundException: ./private/https_leonardo/META-INF/mime.types (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileReader.<init>(FileReader.java:72)
        at com.sun.activation.registries.MimeTypeFile.<init>(MimeTypeFile.java:48)
        at javax.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:246)
        at joliex.io.FileService.setMimeTypeFile(FileService.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at jolie.runtime.JavaService.requestResponseCallable(JavaService.java:244)
        at jolie.runtime.JavaService.callOperation(JavaService.java:337)
        at jolie.runtime.embedding.JavaCommChannel.sendImpl(JavaCommChannel.java:81)
        at jolie.runtime.embedding.JavaCommChannel.send(JavaCommChannel.java:73)
        at jolie.process.SolicitResponseProcess.run(SolicitResponseProcess.java:123)
        at jolie.process.SequentialProcess.run(SequentialProcess.java:59)
        at jolie.process.ScopeProcess$Execution.runScope(ScopeProcess.java:63)
        at jolie.process.ScopeProcess$Execution.run(ScopeProcess.java:50)
        at jolie.process.ScopeProcess.run(ScopeProcess.java:116)
        at jolie.process.DefinitionProcess.run(DefinitionProcess.java:46)
        at jolie.process.InitDefinitionProcess.run(InitDefinitionProcess.java:91)
        at jolie.SessionThread.runProcess(SessionThread.java:468)
        at jolie.ExecutionThread.run(ExecutionThread.java:469)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Feb 23, 2018 12:46:07 PM jolie.Interpreter logInfo
INFO: [test.ol] 
```

**Comment by bmaschio** [comment] 2018-02-23 12:12
@fmontesi 

yea ok how would you test the default operation in a HTTPS?

Balint

**Comment by bmaschio** [comment] 2018-02-23 14:11
@fmontesi 

I tried to do it I have some problems with it 

- I have added am output port to the file /extensions/https.ol


````js
outputPort HttpsOutput {
  Location:"socket://localhost:14001"
  Protocol: https {
	   .keepAlive = false; // Keep connections open
	   .debug = DebugHttp;
	   .debug.showContent = DebugHttpContent
		 .ssl.keyStore = "./extensions/private/https_leonardo/ssl/KeyStore.jks";
		 .ssl.keyStorePassword ="a4KPCrUxShYsjkhQ"

   }
   Interfaces: HTTPInterface
}
````

- After I added the embedding 

````
embedded {
Jolie:
	"./extensions/private/leonardo_https.ol" in HttpsOutput
}
````
And here is where I started to have some problems with it I keep getting operation not defined in inputPort   

````
embedded {
Jolie:
	"./extensions/private/leonardo_https.ol" 
}
````

If I do this I get a generic SSL error 

Help!!!
Balint

**Comment by fmontesi** [comment] 2018-02-24 08:59
Hi Balint,

You're almost there. You just need an alias in the output port of the
client. You want to alias default to "jquery-1.12.2.js" and to use "get" as
method.

However, I'm not so sure that what you're testing here is different than
what `server.ol` is already testing for (notice that it contains an HTTPS
test), aside from the fact that the content of the message comes from
reading a file, which shouldn't make a difference.

So instead of making a new test, you might try putting the exchanges in
`server.ol` inside of a loop. If that works, then your problem might come
from browser-jolie interaction, instead of just jolie. Another difference I
see with `server.ol` is that you're using `.keepAlive = false`, which is
going to open a socket for each download. That's pretty wasteful in https,
so I wouldn't recommend it, but it's still interesting to see whether
that's the cause of the problem.

Cheers,
Fabrizio

**Comment by bmaschio** [comment] 2018-02-27 14:16
Hi @fmontesi 
Still having problems I have defined the alias on the caller Output Port 

````
outputPort HttpsOutput {
  Location:"socket://localhost:14001"
  Protocol: https {
	   .keepAlive = false; // Keep connections open
		 .debug = 1;
		 .debug.showContent = 1;
		 .osc.default.alias = "js/jquery-1.12.2.js";
		 .ssl.keyStore = "./extensions/private/https_leonardo/ssl/KeyStore.jks";
		 .ssl.keyStorePassword ="a4KPCrUxShYsjkhQ"

   }
   Interfaces: HTTPInterface
}
````

in the called service 


````
interface HTTPInterface {
RequestResponse:
	default(undefined)(undefined)
}

inputPort HttpsInput {
  Location:"socket://localhost:14001"
  Protocol: https {
	   .keepAlive = false; // Keep connections open
	   .debug = 1;
	   .debug.showContent = 1;
	   .format -> format;
		 .default= "default";
	   .contentType -> mime;
     .statusCode -> statusCode;
		 .ssl.keyStore = "./extensions/private/https_leonardo/ssl/KeyStore.jks";
		 .ssl.keyStorePassword ="a4KPCrUxShYsjkhQ"
   }
   Interfaces: HTTPInterface
}
````
and I keep getting
AVVERTENZA: [leonardo_https.ol] Received a message for operation default, not specified in the input port at the receiving service. Se
the caller.

**Comment by bmaschio** [comment] 2018-03-02 11:31
@thesave 
I need a bit of help on this
Cheers 
Balint

**Comment by thesave** [comment] 2018-03-07 16:07
Hi @bmaschio, I started working on this.

I found the "killing" behaviour is due to an infinite loop between the UNWRAP and BUFFER_UNDERFLOW statues in the SSL handshake. I wrote a patch (in my local copy, for the time being) and it works.

However it seems we have some problem handling "big" files over HTTPS, i.e., the tiny HTML page in your example transfers correctly as well as the included CSS, however the (big) jquery file fails. I obtained the same result by trying to transfer a large HTML file (a wikipedia page).

I'll further investigate the issue.

As a side-note, the "bad" behaviour discussed above is particularly evident when making requests with other protocols, e.g., HTTP. In that case we were not handling handshake closure correctly and we continued spinning indefinitely to get some data. I also patched that behaviour.

**Comment by bmaschio** [comment] 2018-03-08 08:41
Hi @thesave 
How can I help?

cheers 

Balint

**Comment by thesave** [comment] 2018-03-22 12:50
Hi @bmaschio, [this commit](https://github.com/jolie/jolie/commit/1d2a46056b86c7507f9c9dd05a350840f632d4c2) should fix the misbehaviours you were experiencing.

Can you please confirm if the issue has been resolved?

**Comment by mwallnoefer** [comment] 2018-03-23 20:28
The commit was merged also into the _java6_ branch, since it is a pretty fundamental issue. Thanks Saverio for your deep investigation.

**Comment by fmontesi** [comment] 2018-06-13 16:41
@jolie/developers Can we close this?

**Comment by mwallnoefer** [comment] 2018-06-13 17:45
@fmontesi : I have been waiting for @bmaschio, but yes I think that you can close it.

**Comment by fmontesi** [comment] 2018-06-13 19:47
I'm closing it for now then. @bmaschio feel free to reopen if it appears again.

**Closed by fmontesi** 2018-06-13 19:47 UTC
Labels: bad format, bug
