### ISSUE TITLE
Operators "<<" and "->" not accepted in on-the-fly argument creation

### ISSUE THREAD

**Issue by pgb1968** [jolie/jolie#92] opened 2016-08-27 11:29 UTC
Hi,

I wrote a service receiving a string and a vector of strings, and I was trying to invoke it by passing to it some existing values stored in variables (eg. name, vnames) via an on-the-fly construction, something like:

myFunction@DbService({.name = name ,  .namesvector << vnames})(result);

Alas the parser does not like it: it seems to await only "=" inside the argument construction. But of course for passing the vector it's not correct - it copies just the first element.
So I need to write

req.name = name;
req.namesvector << vnames;
myFunction@DbService(req)(result);

(Same thing if I use "->")
Imho it would be nice, consistent and convenient to be able to do use "<<" and "->" as well as "="...

**Comment by bmaschio** [comment] 2016-08-28 16:25
Hi @pgb1968 

Not sure if  this answers your question  but when I need to construct complex structure I normally use the keyword `with`
I would write something like 
```
with (req){
   nodeName = someValue ;
   nodeName1 = someValue1 
 }
```
The operator << and  -> are used to manipulate trees and in jolie all nodes can be vector by this i mean  that one could write 
```
req,nodeName = "someValue";
or
req.nodeName[0] = "someValue"; 
```
so when you are  writing

```
someStructure << a.b 
is like 
someStructure < a[0].b[0]; 
```
so if b would have some children you would end coping all the subnodes
I tried to replicate your problem and I came out with something like this  
```
 vnames[0]= "FirstValue";
 vnames[1]= "SecondValue";
 vnames[2]= "ThirdValue";

 valueToPrettyString@StringUtils(a)(s);
 println@Console("a" + s)();

  for ( counter =0 , counter < #vnames , counter++){
		 println@Console("vnames[" + counter + "]= " + vnames[counter] )()
	}
```

**Comment by pgb1968** [comment] 2016-08-28 20:50
HI Balint,

thanks for the detailed response, though I am not sure to get all of it, due also to an extensive dinner with wine ;-) However tomorrow I won't  be able to analyze further, so...

What I need to do really, is to implement a sub-service B that is invoked by another service A over an argument req which results from the "composition" of different pieces of structures known to A: just for example, a single string s, and a vectors of strings v. So req must be a tree where a node must contain s, and another node must contain the deep copy of v (or the reference to it), but not only one element of it.

And since I am lazy and I like compact code, I hoped to do this in a single line while invoking B, without having to declare and fill req.  I thought I could use "<<" directly into the call, like B@Service({ .str = s,  .vector << v})(), but not... so, do I have to declare req and fill it?
(No major issue though:  I can go over my laziness if needed. But is there a conceptual reason for "<<" and "->" not to work inside the call B({ ... }) ?    )

Thanks, cheers, 

  Pg

**Comment by fmontesi** [comment] 2016-08-29 07:56
@bmaschio Aside from convenience (code is shorter and sometimes cleaner), an important reason for using an inline tree is that you're not using a variable to store the tree, so after the communication is done  memory gets freed immediately.

Closing because duplicate of #8 , but feel free to continue the discussion there.

**Closed by fmontesi** 2016-08-29 07:56 UTC
Labels: duplicate
