### ISSUE TITLE
Error on concurrent execution

### ISSUE THREAD

**Issue by dfermi** [jolie/jolie#228] opened 2020-05-08 16:05 UTC
Hi all,

I'm a student and I'm working with Jolie just from one week, for a student project in University in Bologna (Italy). 

When executing simple server/client code the following exception is thrown:

```
Exception in thread "serverProf.ol-serverProf.ol-SelectorThread" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at jolie.net.SocketCommChannel._isOpenImpl(SocketCommChannel.java:140)   
        at jolie.util.Helpers.lockAndThen(Helpers.java:149)
        at jolie.net.SocketCommChannel.isOpenImpl(SocketCommChannel.java:181)    
        at jolie.net.CommChannel.isOpen(CommChannel.java:173)
        at jolie.net.CommCore$SelectorThread.lambda$runKeys$0(CommCore.java:821) 
        at jolie.net.CommCore$SelectorThread.runTasks(CommCore.java:866)
        at jolie.net.CommCore$SelectorThread.run(CommCore.java:881)
```

The "server" code is:

```
include "console.iol"

inputPort Server {
    Location: "socket://localhost:8001"
    Protocol: http
    OneWay: send
    RequestResponse: echo, sum, sub
}

execution{ concurrent }

main 
{
    [ echo( req )( res ) {
        res << req
    } ] { println@Console( req )() }
    [ sum( req )( res ) {
        res = req.x + req.y
    } ] { println@Console( req )() }
    [ sub( req )( res ) {
        res = req.x - req.y
    } ] { println@Console( req )() }
    [ send( req ) ] { println@Console( req )() }
}
```
This is the "client" code (I report just main section):
  ```
echo@Server( { .x=5, .y=1 } )( res ) //;
    println@Console( res.x )()
 
```

The same error happens if I try to run the example from the Communication Ports section of the documentation ([here](https://jolielang.gitbook.io/docs/language-tools-and-standard-library/basics/communication-ports/a_comprehensive_example)).

I use Windows 10, with:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
Jolie 1.9.1  (C) 2006-2020 the Jolie team
```
It's my error or there is something to change in my code?!? 

Thank you for your help!

**Comment by fmontesi** [comment] 2020-05-09 07:59
Duplicate of #225.
You're probably using the Jolie distribution from the thread in #220.

You can fix the error by upgrading to Java 11.

(The upcoming official release of Jolie 1.9.1, due for the second half of May, will work with Java 8.)

**Closed by fmontesi** 2020-05-09 07:59 UTC
